#name, main, version and api are required
name: OneHitKill
main: ExamplePlugin.MainClass
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0.0"
api: ["1.0.0"]

load: POSTWORLD
author: Nukkit Project, @Jankirby
description: My first Nukkit plugin, 
website: https://github.com/Jankirby
commands:
  example:
    description: Example command
    usage: "/onehitkill"
    permission: onehitkill.command
permissions:
  onehitkill.command:
    description: "Allows the user to run the OneHitKill command"
    default: false
